-- Batch 1 seed for regulation_articles
-- Source of structure/page numbers: official tables of contents from FIFA PDFs
-- Note: French/Spanish titles and all previews are working metadata drafts for review.

insert into regulation_articles (
  regulation_id,
  article_number,
  article_key,
  page_number,
  title_en,
  title_fr,
  title_es,
  preview_en,
  preview_fr,
  preview_es,
  sort_order,
  is_active
)
values
(
  (select id from regulations where code = 'FFAR'),
  '1',
  'article-1',
  9,
  'Objectives',
  'Objectifs',
  'Objetivos',
  'Sets out the aims of the Football Agent Regulations.',
  'Énonce les finalités du Règlement des agents de football.',
  'Establece los objetivos del Reglamento de Agentes de Fútbol.',
  1,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '2',
  'article-2',
  9,
  'Scope',
  'Champ d’application',
  'Ámbito de aplicación',
  'Defines when and to whom the regulations apply.',
  'Définit quand et à qui le règlement s’applique.',
  'Define cuándo y a quién se aplica el reglamento.',
  2,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '3',
  'article-3',
  10,
  'National football agent regulations',
  'Règlements nationaux sur les agents de football',
  'Reglamentos nacionales sobre agentes de fútbol',
  'Explains the role of national association rules alongside the FIFA framework.',
  'Explique le rôle des règles des associations nationales aux côtés du cadre de la FIFA.',
  'Explica el papel de las normas de las asociaciones nacionales junto con el marco de la FIFA.',
  3,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '4',
  'article-4',
  12,
  'General provisions',
  'Dispositions générales',
  'Disposiciones generales',
  'Introduces the general rules for becoming a football agent.',
  'Présente les règles générales pour devenir agent de football.',
  'Introduce las reglas generales para convertirse en agente de fútbol.',
  4,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '5',
  'article-5',
  12,
  'Eligibility requirements',
  'Conditions d’éligibilité',
  'Requisitos de elegibilidad',
  'Lists the eligibility conditions applicants must satisfy to obtain a licence.',
  'Énumère les conditions d’éligibilité que les candidats doivent remplir pour obtenir une licence.',
  'Enumera las condiciones de elegibilidad que deben cumplir los solicitantes para obtener una licencia.',
  5,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '6',
  'article-6',
  13,
  'Exam procedure',
  'Procédure d’examen',
  'Procedimiento del examen',
  'Describes how the football agent exam is organised and administered.',
  'Décrit l’organisation et l’administration de l’examen d’agent de football.',
  'Describe cómo se organiza y administra el examen de agente de fútbol.',
  6,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '7',
  'article-7',
  13,
  'Licence fee',
  'Frais de licence',
  'Tasa de licencia',
  'Covers the fee payable for the football agent licence.',
  'Couvre les frais à payer pour la licence d’agent de football.',
  'Regula la tasa pagadera por la licencia de agente de fútbol.',
  7,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '8',
  'article-8',
  13,
  'Issue of licence',
  'Délivrance de la licence',
  'Expedición de la licencia',
  'Deals with the granting of a football agent licence after approval.',
  'Traite de l’octroi de la licence d’agent de football après approbation.',
  'Regula la concesión de la licencia de agente de fútbol tras su aprobación.',
  8,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '9',
  'article-9',
  14,
  'Continuing professional development',
  'Développement professionnel continu',
  'Desarrollo profesional continuo',
  'Sets ongoing learning requirements for licensed football agents.',
  'Fixe les exigences de formation continue pour les agents de football licenciés.',
  'Establece requisitos continuos de formación para los agentes de fútbol con licencia.',
  9,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '10',
  'article-10',
  14,
  'Request for a suspension or termination of licence',
  'Demande de suspension ou de résiliation de la licence',
  'Solicitud de suspensión o cancelación de la licencia',
  'Explains how a football agent may request suspension or termination of a licence.',
  'Explique comment un agent de football peut demander la suspension ou la résiliation de sa licence.',
  'Explica cómo un agente de fútbol puede solicitar la suspensión o cancelación de una licencia.',
  10,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '11',
  'article-11',
  16,
  'General provisions',
  'Dispositions générales',
  'Disposiciones generales',
  'Introduces the general rules applicable when acting as a football agent.',
  'Présente les règles générales applicables lors de l’exercice de l’activité d’agent de football.',
  'Introduce las reglas generales aplicables al actuar como agente de fútbol.',
  11,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '12',
  'article-12',
  16,
  'Representation',
  'Représentation',
  'Representación',
  'Sets rules on representation arrangements between agents and clients.',
  'Établit les règles relatives aux modalités de représentation entre les agents et les clients.',
  'Establece las reglas sobre los acuerdos de representación entre agentes y clientes.',
  12,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '13',
  'article-13',
  18,
  'Representation of minors',
  'Représentation des mineurs',
  'Representación de menores',
  'Sets additional restrictions and safeguards for representation involving minors.',
  'Prévoit des restrictions et garanties supplémentaires pour la représentation impliquant des mineurs.',
  'Establece restricciones y salvaguardias adicionales para la representación que involucra a menores.',
  13,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '14',
  'article-14',
  19,
  'Service fee – general principles',
  'Honoraires de service – principes généraux',
  'Honorarios de servicio: principios generales',
  'Introduces the core principles governing service fees.',
  'Présente les principes fondamentaux régissant les honoraires de service.',
  'Introduce los principios fundamentales que rigen los honorarios de servicio.',
  14,
  true
),
(
  (select id from regulations where code = 'FFAR'),
  '15',
  'article-15',
  21,
  'Service fee cap',
  'Plafond des honoraires de service',
  'Tope de los honorarios de servicio',
  'Specifies the cap applicable to service fees.',
  'Précise le plafond applicable aux honoraires de service.',
  'Especifica el tope aplicable a los honorarios de servicio.',
  15,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '1',
  'article-1',
  13,
  'Scope',
  'Champ d’application',
  'Ámbito de aplicación',
  'Defines the scope of the RSTP.',
  'Définit le champ d’application du RSTP.',
  'Define el ámbito de aplicación del RETJ.',
  1,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '2',
  'article-2',
  16,
  'Status of players: amateur and professional players',
  'Statut des joueurs : amateurs et professionnels',
  'Estatus de los jugadores: aficionados y profesionales',
  'Defines the categories of amateur and professional players.',
  'Définit les catégories de joueurs amateurs et professionnels.',
  'Define las categorías de jugadores aficionados y profesionales.',
  2,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '3',
  'article-3',
  16,
  'Reacquisition of amateur status',
  'Recouvrement du statut d’amateur',
  'Recuperación de la condición de aficionado',
  'Explains when a player may regain amateur status.',
  'Explique dans quels cas un joueur peut retrouver le statut d’amateur.',
  'Explica cuándo un jugador puede recuperar la condición de aficionado.',
  3,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '4',
  'article-4',
  16,
  'Termination of activity',
  'Cessation d’activité',
  'Cese de la actividad',
  'Deals with the consequences of ceasing football activity.',
  'Traite des conséquences de la cessation de l’activité footballistique.',
  'Trata las consecuencias del cese de la actividad futbolística.',
  4,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '5',
  'article-5',
  18,
  'Registration',
  'Enregistrement',
  'Inscripción',
  'Sets the rules on player registration.',
  'Établit les règles relatives à l’enregistrement des joueurs.',
  'Establece las reglas sobre la inscripción de jugadores.',
  5,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '5bis',
  'article-5bis',
  19,
  'Bridge transfer',
  'Transfert relais',
  'Transferencia puente',
  'Addresses bridge transfers and related restrictions.',
  'Traite des transferts relais et des restrictions correspondantes.',
  'Aborda las transferencias puente y sus restricciones.',
  6,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '6',
  'article-6',
  20,
  'Registration periods',
  'Périodes d’enregistrement',
  'Periodos de inscripción',
  'Regulates the registration periods for players.',
  'Régit les périodes d’enregistrement des joueurs.',
  'Regula los periodos de inscripción de jugadores.',
  7,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '7',
  'article-7',
  21,
  'Player passport',
  'Passeport du joueur',
  'Pasaporte del jugador',
  'Explains the player passport and its registration history function.',
  'Explique le passeport du joueur et sa fonction d’historique d’enregistrement.',
  'Explica el pasaporte del jugador y su función de historial de inscripción.',
  8,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '8',
  'article-8',
  22,
  'Application for registration',
  'Demande d’enregistrement',
  'Solicitud de inscripción',
  'Sets the requirements for applying for registration.',
  'Établit les exigences applicables à une demande d’enregistrement.',
  'Establece los requisitos para solicitar la inscripción.',
  9,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '9',
  'article-9',
  22,
  'International Transfer Certificate',
  'Certificat international de transfert',
  'Certificado de transferencia internacional',
  'Covers the International Transfer Certificate process.',
  'Couvre la procédure du certificat international de transfert.',
  'Regula el procedimiento del certificado de transferencia internacional.',
  10,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '10',
  'article-10',
  23,
  'Loan of professionals',
  'Prêt de joueurs professionnels',
  'Cesión de profesionales',
  'Regulates the loan of professional players.',
  'Régit le prêt des joueurs professionnels.',
  'Regula la cesión de jugadores profesionales.',
  11,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '11',
  'article-11',
  25,
  'Unregistered players',
  'Joueurs non enregistrés',
  'Jugadores no inscritos',
  'Addresses the status and participation of unregistered players.',
  'Traite du statut et de la participation des joueurs non enregistrés.',
  'Aborda el estatus y la participación de jugadores no inscritos.',
  12,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '12',
  'article-12',
  25,
  'Enforcement of disciplinary sanctions',
  'Exécution des sanctions disciplinaires',
  'Ejecución de sanciones disciplinarias',
  'Explains how disciplinary sanctions are enforced across associations.',
  'Explique comment les sanctions disciplinaires sont exécutées entre associations.',
  'Explica cómo se ejecutan las sanciones disciplinarias entre asociaciones.',
  13,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '12bis',
  'article-12bis',
  25,
  'Overdue payables',
  'Arriérés de paiement',
  'Pagos vencidos',
  'Sets rules on overdue payables owed by clubs.',
  'Établit des règles sur les arriérés de paiement dus par les clubs.',
  'Establece reglas sobre pagos vencidos adeudados por los clubes.',
  14,
  true
),
(
  (select id from regulations where code = 'RSTP'),
  '13',
  'article-13',
  28,
  'Respect of contract',
  'Respect du contrat',
  'Respeto del contrato',
  'Affirms the principle that contracts must be respected.',
  'Affirme le principe selon lequel les contrats doivent être respectés.',
  'Afirma el principio de que los contratos deben respetarse.',
  15,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '1',
  'article-1',
  11,
  'Name and headquarters',
  'Nom et siège',
  'Nombre y sede',
  'States FIFA’s name and headquarters.',
  'Indique le nom et le siège de la FIFA.',
  'Establece el nombre y la sede de la FIFA.',
  1,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '2',
  'article-2',
  11,
  'Objectives',
  'Objectifs',
  'Objetivos',
  'Sets out FIFA’s objectives.',
  'Énonce les objectifs de la FIFA.',
  'Establece los objetivos de la FIFA.',
  2,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '3',
  'article-3',
  12,
  'Human rights',
  'Droits humains',
  'Derechos humanos',
  'Confirms FIFA’s commitment to respecting internationally recognised human rights.',
  'Confirme l’engagement de la FIFA à respecter les droits humains internationalement reconnus.',
  'Confirma el compromiso de la FIFA de respetar los derechos humanos internacionalmente reconocidos.',
  3,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '4',
  'article-4',
  12,
  'Non-discrimination, equality and neutrality',
  'Non-discrimination, égalité et neutralité',
  'No discriminación, igualdad y neutralidad',
  'Sets the core principles of non-discrimination, equality and neutrality.',
  'Énonce les principes fondamentaux de non-discrimination, d’égalité et de neutralité.',
  'Establece los principios fundamentales de no discriminación, igualdad y neutralidad.',
  4,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '5',
  'article-5',
  12,
  'Promoting friendly relations',
  'Promotion des relations amicales',
  'Promoción de relaciones amistosas',
  'Addresses the promotion of friendly relations in football.',
  'Traite de la promotion de relations amicales dans le football.',
  'Aborda la promoción de relaciones amistosas en el fútbol.',
  5,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '6',
  'article-6',
  12,
  'Players',
  'Joueurs',
  'Jugadores',
  'Addresses FIFA’s approach to players within its statutory framework.',
  'Traite de l’approche de la FIFA à l’égard des joueurs dans son cadre statutaire.',
  'Aborda el enfoque de la FIFA respecto de los jugadores en su marco estatutario.',
  6,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '7',
  'article-7',
  13,
  'Laws of the Game',
  'Lois du Jeu',
  'Reglas de Juego',
  'Confirms the central role of the Laws of the Game.',
  'Confirme le rôle central des Lois du Jeu.',
  'Confirma el papel central de las Reglas de Juego.',
  7,
  true
),
(
  (select id from regulations where code = 'STATUTES'),
  '8',
  'article-8',
  13,
  'Conduct of bodies, officials and others',
  'Conduite des organes, des officiels et des autres personnes',
  'Conducta de los órganos, oficiales y otras personas',
  'Sets conduct expectations for bodies, officials and other persons.',
  'Fixe les attentes en matière de conduite pour les organes, les officiels et les autres personnes.',
  'Establece expectativas de conducta para los órganos, oficiales y otras personas.',
  8,
  true
),
(
  (select id from regulations where code = 'FCE'),
  '1',
  'article-1',
  10,
  'Scope of applicability',
  'Champ d’application',
  'Ámbito de aplicación',
  'Defines the scope of application of the Code of Ethics.',
  'Définit le champ d’application du Code d’éthique.',
  'Define el ámbito de aplicación del Código de Ética.',
  1,
  true
),
(
  (select id from regulations where code = 'FCE'),
  '2',
  'article-2',
  10,
  'Persons covered',
  'Personnes visées',
  'Personas sujetas',
  'Identifies the persons bound by the Code of Ethics.',
  'Identifie les personnes liées par le Code d’éthique.',
  'Identifica a las personas sujetas al Código de Ética.',
  2,
  true
),
(
  (select id from regulations where code = 'FCE'),
  '3',
  'article-3',
  10,
  'Applicability in time',
  'Application dans le temps',
  'Aplicación temporal',
  'Explains the temporal application of the Code of Ethics.',
  'Explique l’application temporelle du Code d’éthique.',
  'Explica la aplicación temporal del Código de Ética.',
  3,
  true
),
(
  (select id from regulations where code = 'FCE'),
  '4',
  'article-4',
  10,
  'Scope of the Code, omissions, custom, doctrine and jurisprudence',
  'Portée du Code, lacunes, coutume, doctrine et jurisprudence',
  'Alcance del Código, omisiones, costumbre, doctrina y jurisprudencia',
  'Sets interpretive rules for applying the Code where issues arise.',
  'Établit des règles d’interprétation pour appliquer le Code lorsque des questions se posent.',
  'Establece reglas interpretativas para aplicar el Código cuando surjan cuestiones.',
  4,
  true
),
(
  (select id from regulations where code = 'FCE'),
  '5',
  'article-5',
  11,
  'Division of the Ethics Committee, division of proceedings',
  'Composition de la Commission d’éthique, répartition des procédures',
  'División de la Comisión de Ética, división de los procedimientos',
  'Explains the chambers of the Ethics Committee and how proceedings are divided.',
  'Explique les chambres de la Commission d’éthique et la répartition des procédures.',
  'Explica las cámaras de la Comisión de Ética y cómo se dividen los procedimientos.',
  5,
  true
),
(
  (select id from regulations where code = 'FCE'),
  '6',
  'article-6',
  13,
  'Basis for sanctions',
  'Fondement des sanctions',
  'Fundamento de las sanciones',
  'Introduces the basis for sanctions under the Code of Ethics.',
  'Présente le fondement des sanctions au titre du Code d’éthique.',
  'Introduce el fundamento de las sanciones en virtud del Código de Ética.',
  6,
  true
),
(
  (select id from regulations where code = 'FDC'),
  '1',
  'article-1',
  7,
  'Object',
  'Objet',
  'Objeto',
  'States the object of the FIFA Disciplinary Code.',
  'Énonce l’objet du Code disciplinaire de la FIFA.',
  'Establece el objeto del Código Disciplinario de la FIFA.',
  1,
  true
),
(
  (select id from regulations where code = 'FDC'),
  '2',
  'article-2',
  7,
  'Scope of application: substantive law',
  'Champ d’application : droit matériel',
  'Ámbito de aplicación: derecho sustantivo',
  'Defines the substantive scope of the FIFA Disciplinary Code.',
  'Définit le champ d’application matériel du Code disciplinaire de la FIFA.',
  'Define el ámbito sustantivo del Código Disciplinario de la FIFA.',
  2,
  true
),
(
  (select id from regulations where code = 'FDC'),
  '3',
  'article-3',
  7,
  'Scope of personal application',
  'Champ d’application personnel',
  'Ámbito de aplicación personal',
  'Identifies who is subject to the FIFA Disciplinary Code.',
  'Identifie les personnes soumises au Code disciplinaire de la FIFA.',
  'Identifica quiénes están sujetos al Código Disciplinario de la FIFA.',
  3,
  true
),
(
  (select id from regulations where code = 'FDC'),
  '4',
  'article-4',
  7,
  'Scope of temporal application',
  'Champ d’application temporel',
  'Ámbito de aplicación temporal',
  'Explains the temporal application of the FIFA Disciplinary Code.',
  'Explique l’application temporelle du Code disciplinaire de la FIFA.',
  'Explica la aplicación temporal del Código Disciplinario de la FIFA.',
  4,
  true
),
(
  (select id from regulations where code = 'GUARDIANS'),
  'Principle 1',
  'principle-1',
  12,
  'We will act in the best interests of children',
  'Nous agirons dans l’intérêt supérieur des enfants',
  'Actuaremos en el interés superior de los niños',
  'States that safeguarding decisions should be guided by the best interests of children.',
  'Énonce que les décisions de sauvegarde doivent être guidées par l’intérêt supérieur des enfants.',
  'Establece que las decisiones de salvaguardia deben guiarse por el interés superior de los niños.',
  1,
  true
),
(
  (select id from regulations where code = 'GUARDIANS'),
  'Step 1',
  'step-1',
  19,
  'How are children involved in our game and what safeguards already exist?',
  'Comment les enfants participent-ils à notre jeu et quelles garanties existent déjà ?',
  '¿Cómo participan los niños en nuestro deporte y qué salvaguardias existen ya?',
  'Starts the safeguarding assessment by identifying children''s involvement and existing protections.',
  'Commence l’évaluation de la sauvegarde en identifiant la participation des enfants et les protections déjà en place.',
  'Inicia la evaluación de salvaguardia identificando la participación de los niños y las protecciones ya existentes.',
  2,
  true
);
